### ISSUE TITLE
Gradle Won't Build

### ISSUE THREAD

**Issue by boredhero** [boredhero/morefuelsmod-1.14#3]
Gradle commands all fail with mysterious errors that don't make sense and seem like it isn't able to find/see/import forge. There is no real issue with the OreGen class. I have verified that those imports and features exist in 1.15.2 and are being used correctly (they also worked flawlessly in 1.14.4). The issue seems to be with the Gradle and project configuration but I'm not sure what. 

With the current configuration, all gradle builds fail with an error something like:
```> Configure project :
Deprecated MinecraftExtension.setMappings called. Use mappings(channel, version)
New Dep: net.minecraftforge:forge:1.15.2-31.2.0_mapped_snapshot_20200519-1.15.1

> Task :compileJava FAILED
/home/noah/code/morefuelsmod/src/main/java/io/morefuelsmod/MFMOreGen.java:75: error: cannot find symbol
                                        biome.addFeature(GenerationStage.Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(stoneType, wantedBlock.getDefaultState(), veinSize), Placement.COUNT_RANGE, cfg));
                                                                                                           ^
  symbol:   method createDecoratedFeature(Feature<OreFeatureConfig>,OreFeatureConfig,Placement<CountRangeConfig>,CountRangeConfig)
  location: class Biome
/home/noah/code/morefuelsmod/src/main/java/io/morefuelsmod/MFMOreGen.java:96: error: cannot find symbol
                        biome.addFeature(GenerationStage.Decoration.UNDERGROUND_ORES, Biome.createDecoratedFeature(Feature.ORE, new OreFeatureConfig(stoneType, wantedBlock.getDefaultState(), veinSize), Placement.COUNT_RANGE, cfg));
                                                                                           ^
  symbol:   method createDecoratedFeature(Feature<OreFeatureConfig>,OreFeatureConfig,Placement<CountRangeConfig>,CountRangeConfig)
  location: class Biome
2 errors
FAILURE: Build failed with an exception.```

**Comment by matshou** [comment]
From looking at the error message itself it's clear what the issue is:
`Deprecated MinecraftExtension.setMappings called. Use mappings(channel, version)`

You are using a deprecated declaration method to set mappings.

I've cloned the repository and will fix this as soon as Gradle 4.9 downloads..,
You should really switch to 4.10 to make it easier for other devs :stuck_out_tongue:

**Comment by boredhero** [comment]
@yooksi thanks. Isn't 4.9 what forge comes bundled with though?

**Comment by matshou** [comment]
No, `4.10.3` is the version used by latest 1.15.2 Forge version.

**Comment by matshou** [comment]
After further inspection this issue is not caused by Gradle, but by a call to an unknown method.
`Biome.createDecoratedFeature` is a method that does not exist, where did you get this method?

**Comment by boredhero** [comment]
> After further inspection this issue is not caused by Gradle, but by a call to an unknown method.
> `Biome.createDecoratedFeature` is a method that does not exist, where did you get this method?

Oh noooo. It worked in 1.14 and back. Perhaps it was depreciated. I'll have to replace. Thanks anyways

**Comment by matshou** [comment]
I've fixed build errors from this issue in branch [issue-3](https://github.com/boredhero/morefuelsmod/tree/issue-3), see if it works for you.

If the solution resolves the issue just remember to merge the branch with a commit that auto closes this issue. Use the `--no-ff` switch when merging and add the closure keyword for this issue.

Alternatively just report here and I can do it, not a problem.
