### ISSUE TITLE
Bituminous Coal Ore drops Coke

### ISSUE THREAD

**Issue by boredhero** [boredhero/morefuelsmod-1.14#8]
Which is intended to be the product of smelting Bituminous Coal, making the latter unobtainable. 

Porting this issue over from the [old repo](https://github.com/boredhero/morefuelsmod-1.12). Thanks to @esotericdesign for reporting this.

**Comment by esotericdesign** [comment]
Just reporting: the thing works like a charm. Thanks again! :)
![2020-09-23_08 07 03](https://user-images.githubusercontent.com/40729240/93970481-dfbe9980-fd76-11ea-80d1-4cd78e6451a5.png)
